name: Converter

on: workflow_dispatch

env:
  JSONOUTPUT: "{\"node\":[10, 12, 14]}"

jobs:
  converter:
    name: Run converter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: fabasoad/yaml-json-xml-converter-action@main
        id: yaml2json
        with:
          path: 'inputyaml.yml'
          from: 'yaml'
          to: 'json'
      - id: set-matrix
        run: echo "::set-output name=matrix::$JSONOUTPUT"
      
  job2:
    needs: converter
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJSON(needs.converter.outputs.matrix)}}
    steps:
      - run: echo "The version is ${{ matrix.node }}"
