name: Converter

on: workflow_dispatch

env:
  MATRIX: "{\"node\":[17, 24, 11]}"

jobs:
  converter:
    name: Run converter
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v1
      - uses: fabasoad/yaml-json-xml-converter-action@main
        id: yaml2json
        with:
          path: 'inputyaml.yml'
          from: 'yaml'
          to: 'json'
      - id: set-matrix
        run: echo "::set-output name=matrix::$MATRIX"
      
  job2:
    needs: converter
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix: ${{fromJSON(needs.converter.outputs.matrix)}}
    steps:
      - run: | 
               sleep 5
               echo "The version is ${{ matrix.node }}"
               echo "The job id is ${{ github.job }}"

  job3:
    needs: [converter, job2]
    runs-on: ubuntu-latest
    steps:
      - run: | 
               echo "Hello, I am job3!"
