name: Get YML Path

on: 
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Who to greet
        options: 
        - monalisa
        - cschleiden

jobs:
  getymlpath:
    runs-on: ubuntu-latest

    steps:
    - name: Get YML
      uses: CumulusDS/get-yaml-paths-action@v0.1.0
      with:
        file: testyaml.yml
        machine1_name: machines.machine1.name
      run: |
        echo $machines.machine1.name
