name: Read Config Keys
on:
  workflow_dispatch:

jobs:
  read-config:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Read Config Keys
        run: |
          # Retrieve the JSON data from the configuration variable
          echo "${{ fromJson(vars.MYDATA2).name }}"
