name: Get YML Path

on: 
  workflow_dispatch:

jobs:
  getymlpath:
    runs-on: ubuntu-latest

    steps:
    - name: Get YML
      uses: @cumulusds@v0.0.0
      with:
        file: testyaml.yml
        machine1_name: machines.machine1.name
      run: |
        echo $machines.machine1.name
