name: Get YML Path

on: 
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Who to greet
        options: 
        - monalisa
        - cschleiden

jobs:
  getymlpath:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.0
    
    - name: Get YML
      id: getyml
      uses: CumulusDS/get-yaml-paths-action@v0.1.0
      with:
        file: inputyaml.yml
        foo: machines.machine1.name
        
    - name: Yamler
      id: yamler
      uses: the-coding-turtle/ga-yaml-parser@v0.1
      with:
        directory: "config.yaml"

    - name: Echo
      run: echo "The name is ${{ steps.yamler.outputs.machines_machine1_name }}"
