name: Converter

on: workflow_dispatch

env:
  JSON_OUTPUT: "{\"node\":[\"A\", \"B\", \"C\"]}"

jobs:
  converter:
    name: Run converter
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ env.JSON_OUTPUT }}
    steps:
      - uses: actions/checkout@v1
      - uses: fabasoad/yaml-json-xml-converter-action@main
        id: yaml2json
        with:
          path: 'inputyaml.yml'
          from: 'yaml'
          to: 'json'
  job2:
    needs: converter
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJSON(needs.converter.outputs.matrix)}}
    steps:
      - run: echo "The version is ${{ matrix.node }}"
