name: Get YML Path

on: 
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Who to greet
        options: 
        - monalisa
        - cschleiden

jobs:
  getymlpath:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.0
    
    - name: Get YML
      uses: CumulusDS/get-yaml-paths-action@v0.1.0
      with:
        file: inputyaml.yml
