name: Matrix Loops

on: 
  workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10, 12, 14]
    steps:
         - name: Echo
           run: echo "The version is ${{ matrix.node }}"
