name: Converter

on: workflow_dispatch

env:
  MATRIX: "{\"machines\":{\"machine1\":{\"name\":\"M1\",\"size\":\"small\",\"apps\":[\"java\",\"dotnet\"]},\"machine2\":{\"name\":\"M2\",\"size\":\"large\"}}}"

jobs:
  converter:
    name: Run converter
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v1
      - uses: fabasoad/yaml-json-xml-converter-action@main
        id: yaml2json
        with:
          path: 'inputyaml.yml'
          from: 'yaml'
          to: 'json'
      - id: set-matrix
        run: echo "::set-output name=matrix::$MATRIX"
      
  job2:
    needs: converter
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJSON(needs.converter.outputs.matrix)}}
    steps:
      - run: echo "The version is ${{ matrix.machines.machine1.apps }}"
