name: Converter

on: workflow_dispatch

env:
  JSON_OUTPUT: "{\"machines\":{\"machine1\":{\"name\":\"M1\",\"size\":\"small\",\"apps\":[\"java\",\"dotnet\"]},\"machine2\":{\"name\":\"M2\",\"size\":\"large\"}}}"

jobs:
  converter:
    name: Run converter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: fabasoad/yaml-json-xml-converter-action@main
        id: yaml2json
        with:
          path: 'inputyaml.yml'
          from: 'yaml'
          to: 'json'
  job2:
    needs: converter
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJSON(env.JSON_OUTPUT)}}
    steps:
      - run: echo "The version is ${{ matrix.machines.machine1.apps }}"
