name: Converter

on: workflow_dispatch

jobs:
  converter:
    name: Run converter
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v1
      - uses: fabasoad/yaml-json-xml-converter-action@main
        id: yaml2json
        with:
          path: 'inputyaml.yml'
          from: 'yaml'
          to: 'json'
      - name: Add Environment variable
        run: echo "json_output=${{ steps.yaml2json.outputs.data }}" | sed 's/"/\\"/g' >> $GITHUB_ENV
      - id: set-matrix
        run: echo "::set-output name=matrix::${{ env.json_output }}"
  job2:
    needs: converter
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJSON(needs.converter.outputs.matrix)}}
    steps:
      - run: echo "The version is ${{ matrix.machines.machine1.apps }}"
